---
name: "actions-ping"
description: "Official Github Action for deploying apps to a Dokku installation"
author: "elementing"
branding:
  icon: "upload-cloud"
  color: "blue"
inputs:
  url:
    description: "the url to ping"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  entrypoint: "/entrypoint.sh"
  env:
    PING_URL: ${{ inputs.url }}